### ISSUE TITLE
環境構築を楽にしたい

### ISSUE THREAD

**Issue by yakult1995** [ry-itto/techfest_frontend#1]
使用ライブラリの依存関係などを考えたくないので`Dockerfile`などを作成していただくことは可能でしょうか？

**Comment by ry-itto** [comment]
すみませんつくります！！！！！

**Comment by k-nasa** [comment]
丁寧口調なのが逆に怖い、、

**Comment by yakult1995** [comment]
https://github.com/ry-itto/techfest_frontend/tree/docker

**Comment by yakult1995** [comment]
Reactビルドするための`Dockerfile`追加しました。:tada:

**Comment by yakult1995** [comment]
* [ ] ビルドの成果物をホストOSにコピーする環境の整備

**Comment by yakult1995** [comment]
#5

**Comment by yakult1995** [comment]
とりあえず手動デプロイ出来る機構は整ったのでclose
